export type AceTheme = {
  text: string;
  name: string;
  colorTxt: string;
  colorBg: string;
  colorTxtSel: string;
  colorBgSel: string;
  colorHover: string;
};

export const AceThemes: AceTheme[] = [
  {
    text: "Ambiance",
    name: "ambiance",
    colorTxt: "#e6e1dc",
    colorBg: "#202020",
    colorTxtSel: "#E6E1DC",
    colorBgSel: "#272727",
    colorHover: "#ec5e2c",
  },
  {
    text: "Chaos",
    name: "chaos",
    colorTxt: "#E6E1DC",
    colorBg: "#161616",
    colorTxtSel: "#e6e1dc",
    colorBgSel: "#333333",
    colorHover: "#f0202d",
  },
  {
    text: "Chrome",
    name: "chrome",
    colorTxt: "#303030",
    colorBg: "#ffffff",
    colorTxtSel: "#303030",
    colorBgSel: "#ededed",
    colorHover: "#981084",
  },
  {
    text: "Clouds",
    name: "clouds",
    colorTxt: "#262626",
    colorBg: "#ffffff",
    colorTxtSel: "#262626",
    colorBgSel: "#fffbd1",
    colorHover: "#c92766",
  },
  {
    text: "Clouds Midnight",
    name: "clouds_midnight",
    colorTxt: "#929292",
    colorBg: "#191919",
    colorTxtSel: "#929292",
    colorBgSel: "#1f1f1f",
    colorHover: "#cb201a",
  },
  {
    text: "Cobalt",
    name: "cobalt",
    colorTxt: "#ffffff",
    colorBg: "#002240",
    colorTxtSel: "#ffffff",
    colorBgSel: "#00162a",
    colorHover: "#ffef85",
  },
  {
    text: "Crimson Editor",
    name: "crimson_editor",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#e8f2fe",
    colorHover: "#0000ff",
  },
  {
    text: "Dawn",
    name: "dawn",
    colorTxt: "#212121",
    colorBg: "#f9f9f9",
    colorTxtSel: "#212121",
    colorBgSel: "#dfe7f1",
    colorHover: "#a71d5d",
  },
  {
    text: "Dracula",
    name: "dracula",
    colorTxt: "#f8f8f2",
    colorBg: "#282a36",
    colorTxtSel: "#f8f8f2",
    colorBgSel: "#44475a",
    colorHover: "#bd93f9",
  },
  {
    text: "DreamWeaver",
    name: "dreamweaver",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#ededed",
    colorHover: "#0000ff",
  },
  {
    text: "Eclipse",
    name: "eclipse",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#e8f2fe",
    colorHover: "#7f0055",
  },
  {
    text: "GitHub",
    name: "github",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#f5f5f5",
    colorHover: "#009999",
  },
  {
    text: "Gob",
    name: "gob",
    colorTxt: "#00f007",
    colorBg: "#0b0b0b",
    colorTxtSel: "#00f007",
    colorBgSel: "#151515",
    colorHover: "#14b3e8",
  },
  {
    text: "GruvBox",
    name: "gruvbox",
    colorTxt: "#ebdab4",
    colorBg: "#1d2021",
    colorTxtSel: "#ebdab4",
    colorBgSel: "#3c3836",
    colorHover: "#8ec07c",
  },
  {
    text: "Idle Fingers",
    name: "idle_fingers",
    colorTxt: "#fffff2",
    colorBg: "#323232",
    colorTxtSel: "#fffff2",
    colorBgSel: "#353637",
    colorHover: "#cc6132",
  },
  {
    text: "IPlastic",
    name: "iplastic",
    colorTxt: "#333333",
    colorBg: "#eeeeee",
    colorTxtSel: "#333333",
    colorBgSel: "#e5e5e5",
    colorHover: "#3333fc",
  },
  {
    text: "Katzenmilch",
    name: "katzenmilch",
    colorTxt: "#212121",
    colorBg: "#f3f2f3",
    colorTxtSel: "#212121",
    colorBgSel: "#e8f2fe",
    colorHover: "#674ab9",
  },
  {
    text: "Kr Theme",
    name: "kr_theme",
    colorTxt: "#fbfded",
    colorBg: "#0b0a09",
    colorTxtSel: "#fbfded",
    colorBgSel: "#38403d",
    colorHover: "#ffe366",
  },
  {
    text: "Kuroir",
    name: "kuroir",
    colorTxt: "#212121",
    colorBg: "#e8e9e8",
    colorTxtSel: "#212121",
    colorBgSel: "#e2e6bf",
    colorHover: "#a52a2a",
  },
  {
    text: "Merbivore",
    name: "merbivore",
    colorTxt: "#e6e1dc",
    colorBg: "#161616",
    colorTxtSel: "#e6e1dc",
    colorBgSel: "#333435",
    colorHover: "#fc6f09",
  },
  {
    text: "Merbivore Soft",
    name: "merbivore_soft",
    colorTxt: "#E6E1DC",
    colorBg: "#1c1c1c",
    colorTxtSel: "#e6e1dc",
    colorBgSel: "#333435",
    colorHover: "#fc803a",
  },
  {
    text: "Mono Industrial",
    name: "mono_industrial",
    colorTxt: "#fffff2",
    colorBg: "#222c28",
    colorTxtSel: "#fffff2",
    colorBgSel: "#1c2421",
    colorHover: "#c23b00",
  },
  {
    text: "Monokai",
    name: "monokai",
    colorTxt: "#f8f8e5",
    colorBg: "#272822",
    colorTxtSel: "#f8f8e5",
    colorBgSel: "#202020",
    colorHover: "#66d9ef",
  },
  {
    text: "Nord Dark",
    name: "nord_dark",
    colorTxt: "#d8dee9",
    colorBg: "#2e3440",
    colorTxtSel: "#d8dee9",
    colorBgSel: "#3f4758",
    colorHover: "#4e89c1",
  },
  {
    text: "One Dark",
    name: "one_dark",
    colorTxt: "#abb2bf",
    colorBg: "#282c34",
    colorTxtSel: "#abb2bf",
    colorBgSel: "#2e343d",
    colorHover: "#c678dd",
  },
  {
    text: "Pastel on Dark",
    name: "pastel_on_dark",
    colorTxt: "#8f938f",
    colorBg: "#2c2828",
    colorTxtSel: "#8f938f",
    colorBgSel: "#332f2f",
    colorHover: "#4f6dd8",
  },
  {
    text: "Solarized Dark",
    name: "solarized_dark",
    colorTxt: "#93a1a1",
    colorBg: "#002b36",
    colorTxtSel: "#93a1a1",
    colorBgSel: "#1a414a",
    colorHover: "#859900",
  },
  {
    text: "Solarized Light",
    name: "solarized_light",
    colorTxt: "#586e75",
    colorBg: "#fdf6e3",
    colorTxtSel: "#586e75",
    colorBgSel: "#eee8d5",
    colorHover: "#859900",
  },
  {
    text: "SqlServer",
    name: "sqlserver",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#ededed",
    colorHover: "#11c7e0",
  },
  {
    text: "Terminal",
    name: "terminal",
    colorTxt: "#dedede",
    colorBg: "#000000",
    colorTxtSel: "#dedede",
    colorBgSel: "#2a2a2a",
    colorHover: "#ff6347",
  },
  {
    text: "Textmate",
    name: "textmate",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#ededed",
    colorHover: "#0000ff",
  },
  {
    text: "Tomorrow",
    name: "tomorrow",
    colorTxt: "#4d4d4c",
    colorBg: "#ffffff",
    colorTxtSel: "#4d4d4c",
    colorBgSel: "#efefef",
    colorHover: "#8959a8",
  },
  {
    text: "Tomorrow Night",
    name: "tomorrow_night",
    colorTxt: "#c5c8c6",
    colorBg: "#1d1f21",
    colorTxtSel: "#c5c8c6",
    colorBgSel: "#282a2e",
    colorHover: "#b294bb",
  },
  {
    text: "Tomorrow Night Blue",
    name: "tomorrow_night_blue",
    colorTxt: "#ffffff",
    colorBg: "#002451",
    colorTxtSel: "#ffffff",
    colorBgSel: "#00346e",
    colorHover: "#ebbbff",
  },
  {
    text: "Tomorrow Night Bright",
    name: "tomorrow_night_bright",
    colorTxt: "#dedede",
    colorBg: "#000000",
    colorTxtSel: "#dedede",
    colorBgSel: "#2a2a2a",
    colorHover: "#c397d8",
  },
  {
    text: "Tomorrow Night Eighties",
    name: "tomorrow_night_eighties",
    colorTxt: "#cccccc",
    colorBg: "#2d2d2d",
    colorTxtSel: "#cccccc",
    colorBgSel: "#393939",
    colorHover: "#cc99cc",
  },
  {
    text: "Twilight",
    name: "twilight",
    colorTxt: "#f8f8f8",
    colorBg: "#141414",
    colorTxtSel: "#f8f8f8",
    colorBgSel: "#1b1b1b",
    colorHover: "#cda869",
  },
  {
    text: "Vibrant Ink",
    name: "vibrant_ink",
    colorTxt: "#ffffff",
    colorBg: "#0f0f0f",
    colorTxtSel: "#ffffff",
    colorBgSel: "#333333",
    colorHover: "#9933cc",
  },
  {
    text: "XCode",
    name: "xcode",
    colorTxt: "#212121",
    colorBg: "#ffffff",
    colorTxtSel: "#212121",
    colorBgSel: "#ededed",
    colorHover: "#c800a4",
  },
];
